import { ArrowUpIcon } from "@chakra-ui/icons";
import {
  Box,
  Button,
  Container,
  Flex,
  Heading,
  HStack,
  Image,
  Input,
  List,
  ListItem,
  Text,
  VStack,
} from "@chakra-ui/react";
import Head from "next/head";
import MainLayouts from "../layouts/mainLayouts";
import styles from "../styles/Home.module.css";
import ChakraCarousel from "../components/ChakraCarousel";
import { Link as ChakraLink } from "@chakra-ui/react";

const featureBoxProps = {
  textAlign: "center",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  alignItems: "center",
  flexDirection: "column",
  p: 5,
  backgroundColor: "rgba(47, 50, 65, 0.5)",
  width: "285px",
  borderRadius: "20px",
};

function StatsBox() {
  return (
    <Flex
      borderRadius={"8px"}
      backgroundColor={"rgba(47, 50, 65, 0.5);"}
      minHeight={"178px"}
      width={"346px"}
      mx={"auto"}
      flexDirection={"column"}
      justifyContent={"space-between"}
      p={5}
    >
      <Flex alignItems={"center"} justifyContent={"space-between"}>
        <Image height={"44px"} width={"44px"} src="/icons/btc_icon.png" />
        <Box textAlign={"right"}>
          <Image src="/stats.png" />
          <Text>
            <ArrowUpIcon />
            2.11%
          </Text>
        </Box>
      </Flex>
      <Flex alignItems={"center"} justifyContent={"space-between"}>
        <Heading fontSize={"25px"} as="h4">
          USD 53,260.20
        </Heading>
        <Text>BTC</Text>
      </Flex>
    </Flex>
  );
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Purx Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box minH={{ base: "300px", md: "768px" }} className="main_overlay">
        <Container
          backgroundSize={"100% 100%"}
          backgroundPosition={"center"}
          backgroundRepeat={"no-repeat"}
          backgroundImage={[
            "url(/decorativeline-sm.png)",
            "url(/decorativeline-sm.png)",
            "url(/DecorativeLine.png)",
          ]}
          maxW="container.xl"
        >
          <Flex
            flexDirection={["column", "column", "row", "row"]}
            justifyContent={"space-between"}
          >
            <Box
              textAlign={{ base: "center", md: "left" }}
              width={["100%", "100%", "50%", "50%"]}
            >
              <Heading
                textAlign={{ base: "center", md: "left" }}
                fontSize={["24px", "24px", "32px", "61px"]}
              >
                A trusted and secure cryptocurrency exchange.
              </Heading>
              <Text mx={{ base: "auto", md: "0" }} maxW={"521px"}>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Diam mi
                facilisis tortor ultricies integer. Ante viverra consequat in
                tellus duis. Odio scelerisque eu
              </Text>
              <Button
                color="#fff"
                mt={"48px"}
                borderRadius={"100px"}
                background={"#F47323"}
                height={"65px"}
                maxW={"287px"}
                width={"100%"}
                my={"20px"}
              >
                Download Now
              </Button>
            </Box>
            <Box display={{ base: "none", md: "inline-block" }}>
              <Image
                mx={{ base: "auto", md: "0" }}
                src="/app_preview.png"
                alt="app mobile preview"
              />
            </Box>
          </Flex>
        </Container>
      </Box>
      <Box backgroundColor={"#01081F"}>
        <ChakraCarousel gap={32}>
          <StatsBox />
          <StatsBox />
          <StatsBox />
          <StatsBox />
          <StatsBox />
          <StatsBox />
        </ChakraCarousel>
      </Box>
      <Box
        backgroundSize={"cover"}
        backgroundAttachment={"fixed"}
        backgroundPosition={"center"}
        backgroundRepeat={"no-repeat"}
        backgroundColor={"#01081F"}
        minH={"100vh"}
        backgroundImage={"url(/mapstack.png)"}
      >
        <Container maxW="container.xl">
          <Flex flexDirection={{ base: "column-reverse", md: "row" }}>
            <Flex flexDirection={["column", "column", "column", "row"]}>
              <VStack
                alignItems={"center"}
                justifyContent={"center"}
                mr={{ base: "0", md: 5 }}
              >
                <Box {...featureBoxProps} my="10">
                  <Image src="/icons/con-icon.png" />
                  <Heading my={"10px"} fontSize={["18px","18px","18px","25px"]} as="h3">
                    Heading 1
                  </Heading>
                  <Text>
                    body text goes here,body text goes here,body text goes
                    here,body text goes here,
                  </Text>
                </Box>
                <Box {...featureBoxProps} my="10">
                  <Image src="/icons/phone-icon.png" />
                  <Heading fontSize={["18px","18px","18px","25px"]}  my={"10px"}  as="h3">
                    Heading 1
                  </Heading>
                  <Text>
                    body text goes here,body text goes here,body text goes
                    here,body text goes here,
                  </Text>
                </Box>
              </VStack>
              <VStack alignItems={"center"} justifyContent={"center"}>
                <Box my="10" {...featureBoxProps} width={"285px"}>
                  <Image src="/icons/lock-icon.png" />
                  <Heading fontSize={["18px","18px","18px","25px"]} my={"10px"}  as="h3">
                    Heading 1
                  </Heading>
                  <Text>
                    body text goes here,body text goes here,body text goes
                    here,body text goes here,
                  </Text>
                </Box>
              </VStack>
            </Flex>

            <Flex
              textAlign={{ base: "center", md: "left" }}
              px={[0,0,5,10]}
              flexDirection={"column"}
              justifyContent={"center"}
            >
              <Heading fontSize={["24px","24px","24px","30px"]}>The most trusted cryptocurrency platform.</Heading>
              <Text mx={{ base: "auto", md: "0" }} maxW={"448px"} my={5}>
                body text goes here,body text goes here,body text goes here,body
                text goes here,
              </Text>
              <Button
                color={"#fff"}
                backgroundColor={"#F47323"}
                width={"225px"}
                height={"58px"}
                my={5}
                mx={{ base: "auto", md: "0" }}
              >
                Let's Trade Now
              </Button>
            </Flex>
          </Flex>
        </Container>
      </Box>
      <Box
        backgroundRepeat={"no-repeat"}
        backgroundPosition={"left center"}
        backgroundImage={"url(/circle_right.png)"}
        backgroundColor={"#01081F"}
        py={"120px"}
      >
        <Container maxW="container.xl">
          <Flex
            flexDirection={["column", "column", "row"]}
            justifyContent={"space-between"}
          >
            <Box>
              <Heading
                textAlign={{ base: "center", md: "left " }}
                mx={{ base: "auto", md: 0 }}
                maxW={"568px"}
                fontSize={["24px","24px","24px","30px"]}
              >
                One click, instant payout with credit or debit card.
              </Heading>
              <List mt={5} spacing={10}>
                <ListItem
                  fontSize={{ base: "18px", md: "25px" }}
                  display="flex"
                  alignItems={"center"}
                  justifyContent={[
                    "center",
                    "center",
                    "center",
                    "left",
                    "left",
                  ]}
                  color={"#fff"}
                  ml={[0, 0, 0, 10, 10]}
                >
                  <Image
                    height={["64px", "64px", "91px"]}
                    width={["64px", "64px", "91px"]}
                    mr={5}
                    src="/icons/wallet_icon.png"
                  />
                  Create an account
                </ListItem>
                <ListItem
                  ml={[0, 0, 0, 10, 20]}
                  fontSize={{ base: "18px", md: "25px" }}
                  display="flex"
                  alignItems={"center"}
                  color={"#fff"}
                  justifyContent={[
                    "center",
                    "center",
                    "center",
                    "left",
                    "left",
                  ]}
                >
                  <Image
                    height={["64px", "64px", "91px"]}
                    width={["64px", "64px", "91px"]}
                    mr={5}
                    src="/icons/people_icon.png"
                  />
                  Create an account
                </ListItem>
                <ListItem
                  ml={[0, 0, 0, 10, 40]}
                  fontSize={{ base: "18px", md: "25px" }}
                  display="flex"
                  alignItems={"center"}
                  color={"#fff"}
                  justifyContent={[
                    "center",
                    "center",
                    "center",
                    "left",
                    "left",
                  ]}
                >
                  <Image
                    height={["64px", "64px", "91px"]}
                    width={["64px", "64px", "91px"]}
                    mr={5}
                    src="/icons/bank_icon.png"
                  />
                  Create an account
                </ListItem>
              </List>
            </Box>
            <Box>
              <Image
                my={"10"}
                mx={["auto", "auto", "auto", "0"]}
                src="/phone.png"
                alt="phone"
              />
            </Box>
          </Flex>
        </Container>
      </Box>
      <Box py={"120px"} backgroundColor={"#01081F"}>
        <Container maxW="container.xl">
          <Flex flexDirection={{ base: "column-reverse", lg: "row" }}>
            <Flex alignItems={"center"}>
              <Image mx={{ base: "auto", lg: "0" }} src="/illustration.png" />
            </Flex>
            <Box>
              <Heading
                textAlign={{ base: "center", lg: "left" }}
                fontSize={["24px", "24px", "32px", "49px"]}
              >
                We are the most trusted cryptocurrency platform.
              </Heading>
              <Text textAlign={{ base: "center", lg: "left" }}>
                body text goes here,body text goes here,body text goes here,body
                text goes here,
              </Text>
              <List mt={20} spacing={"20px"}>
                <ListItem
                  justifyContent={{ base: "center", lg: "flex-start" }}
                  as={Flex}
                >
                  <Image
                    height={{ base: "72px", md: "111px" }}
                    width={{ base: "72px", md: "111px" }}
                    mr={10}
                    src="/icons/eyeopen_icon.png"
                  />
                  <Box>
                    <Heading fontSize={{ base: "18px", md: "25px" }}>
                      Heading title 1
                    </Heading>
                    <Text
                      fontSize={{ base: "14px", md: "16px" }}
                      maxW={"309px"}
                    >
                      body text goes here,body text goes here,body text goes
                      here,body text goes here,
                    </Text>
                  </Box>
                </ListItem>
                <ListItem
                  justifyContent={{ base: "center", lg: "flex-start" }}
                  as={Flex}
                >
                  <Image
                    height={{ base: "72px", md: "111px" }}
                    width={{ base: "72px", md: "111px" }}
                    mr={10}
                    src="/icons/secured_icon.png"
                  />
                  <Box>
                    <Heading fontSize={{ base: "18px", md: "25px" }}>
                      Heading title 1
                    </Heading>
                    <Text
                      fontSize={{ base: "14px", md: "16px" }}
                      maxW={"309px"}
                    >
                      body text goes here,body text goes here,body text goes
                      here,body text goes here,
                    </Text>
                  </Box>
                </ListItem>
                <ListItem
                  justifyContent={{ base: "center", lg: "flex-start" }}
                  as={Flex}
                >
                  <Image
                    height={{ base: "72px", md: "111px" }}
                    width={{ base: "72px", md: "111px" }}
                    mr={10}
                    src="/icons/group_icon.png"
                  />
                  <Box>
                    <Heading fontSize={{ base: "18px", md: "25px" }}>
                      Heading title 1
                    </Heading>
                    <Text
                      fontSize={{ base: "14px", md: "16px" }}
                      maxW={"309px"}
                    >
                      body text goes here,body text goes here,body text goes
                      here,body text goes here,
                    </Text>
                  </Box>
                </ListItem>
              </List>
            </Box>
          </Flex>
        </Container>
      </Box>
      <Box
        backgroundSize={"cover"}
        // backgroundAttachment={"fixed"}
        backgroundPosition={"center"}
        backgroundRepeat={"no-repeat"}
        backgroundColor={"#01081F"}
        minH={"100vh"}
        backgroundImage={"url(/mapstack.png)"}
        py={"120px"}
      >
        <Container maxW={"container.xl"}>
          <Flex
            textAlign={{ base: "center", md: "left" }}
            flexDirection={{ base: "column", md: "row" }}
            alignItems={"center"}
          >
            <Box my={10}>
              <Heading maxW={"539px"}>What media says about Cryptolly?</Heading>
              <Text my={"20px"} maxW={"499px"}>
                body text goes here,body text goes here,body text goes here,body
                text goes here,
              </Text>
              <Text
                fontSize={"18px"}
                fontWeight={900}
                color={"#A5ADCF"}
                as="small"
              >
                Newsweek, 2020
              </Text>
            </Box>
            <Box>
              <Image src="/NewsMedia.png" alt="" />
            </Box>
          </Flex>
          <Flex
            textAlign={{ base: "center", md: "left" }}
            flexDirection={{ base: "column-reverse", md: "row" }}
            alignItems={"center"}
          >
            <Box>
              <Image src="/phone_stats.png" alt="" />
            </Box>
            <Box>
              <Heading>Buy airtime and data with crypto </Heading>
              <Text maxW={"402px"}>
                body text goes here,body text goes here,body text goes here,body
                text goes here,
              </Text>
              <Text fontWeight={900} color="#fff" mt={"48px"} mb={"20px"}>
                Get the CryptoVest Wallet Mobile App Now!
              </Text>
              <HStack
                justifyContent={{ base: "center", md: "space-between" }}
                flexWrap={"wrap"}
              >
                <ChakraLink href="#">
                  <Image my={5} mr="10px" src="/GooglePlay.png" />
                </ChakraLink>
                <ChakraLink href="#">
                  <Image m="10px" src="/AppStore.png" />
                </ChakraLink>
              </HStack>
            </Box>
          </Flex>
        </Container>
      </Box>
      <Box
        backgroundPosition={"left center"}
        backgroundRepeat={"no-repeat"}
        backgroundImage={"url(/twisted_line.png)"}
        textAlign={"center"}
        backgroundColor={"#01081F"}
        py={"120px"}
      >
        <Container>
          <Text>Ready to start trading cryptocurrency?</Text>
          <Heading my={"30px"}>
            New users can earn up to $80 in crypto rewards.
          </Heading>
          <Flex
            border={"1px solid #34384C"}
            background={"rgba(47, 50, 65, 0.5)"}
            height={"63px"}
            borderRadius={"100px"}
            alignItems={"center"}
            px={"10px"}
          >
            <Input
              _focus={{
                boxShadow: "none",
              }}
              backgroundColor={"transparent"}
              border={"none"}
              borderRadius={"100px"}
              height={"100%"}
            />
            <Button
              width={"83px"}
              color={"#fff"}
              backgroundColor={"#F47323;"}
              borderRadius={"100px"}
              height={"47px"}
            >
              Send
            </Button>
          </Flex>
        </Container>
      </Box>
    </div>
  );
}

Home.layout = MainLayouts;
